### PR TITLE
Fix NSInternalInconsistencyException issue

### PR DESCRIPTION
**Pull request by kmphua**
Fix issue of NSInternalInconsistencyException occurring at times, reason: 'Invalid parameter not satisfying: isfinite(timeInterval) && !isnan(timeInterval)'.

### CODE REVIEW

**Comment by ChrisMash** [comment]
Thanks for the PR! I had similar code at certain points but found it wasn’t required in the end, so you know what else you changed to need it, or maybe a specific scenario where it happened?

**Comment by kmphua** [comment]
I used your code as is, except that I added an Image an a Button to the VideoPlayerContainerView, and navigated to the VideoView from another View. The exception happened quite frequently like 4 out 5 times.

**Comment by JackYoustra** [comment]
I got the same issue

**Comment by ChrisMash** [comment]
Thanks for the report and effort to raise a PR, I've made my own commit with a slightly different fix to avoid you needing to rework your PR.

**Pull request closed without merging**
